### ISSUE TITLE
com.dmetasoul.lakesoul.meta.entity not exist

### ISSUE THREAD

**Issue by hjfrank1991** [lakesoul-io/LakeSoul#474]
LakeSoul-2.5.3 lakesoul-common com.dmetasoul.lakesoul.meta.entity not exist

**Comment by xuchen-plus** [comment]
Entity files are generated by protobuf. They would be automatically generated when compiling the project. You could also execute 
```bash
mvn protobuf:compile -pl lakesoul-common
```
to generate them manually.
